version: '3.8'

services:
  baul-aliexpress-db:
    image: postgres:latest
    container_name: baul-aliexpress-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '6001:5432'

volumes:
  db-data:
